### ISSUE TITLE
Does not work with /blog/ removal in config.php

### ISSUE THREAD

**Issue by lee-johnson** [FabianSperrle/kirby-stats#13]
I would like to remove the /blog/ folder from URLs for SEO purposes but your stats plugin then does no work. Any ideas why?

/\* remove /blog/ from URLs */
c::set('routes', array(
array(
'pattern' => '(:any)',
'action'  => function($uid) {
$page = page($uid);
if(!$page) $page = page('blog/' . $uid);
if(!$page) $page = site()->errorPage();
return site()->visit($page);
}
),
array(
'pattern' => 'blog/(:any)',
'action'  => function($uid) {
go($uid);
}
)
));

**Comment by FabianSperrle** [comment]
Unfortunately the plugin is not compatible with any other custom routes at the moment. If you still want to use it, drop all the route configuration in the plugin and include the plugin snippet on every page, e.g. in the footer like so:
`snippet('stats', array('param' => $page->uri()));`

**Comment by lee-johnson** [comment]
Thanks Fabian , works a treat.
