### ISSUE TITLE
multi lang issue

### ISSUE THREAD

**Issue by andi242** [FabianSperrle/kirby-stats#3]
commented this out it still gives an error when activating this on a single lang site.

```
c::set('language.detect', true);
c::set('languages', array(
                'code'    => 'de-de',
                'name'    => 'Deutschland',
                'locale'  => 'de_DE',
                'url'     => '/de',
                'default' => true,
                ),
            ));
```

stats widget is now showing up now if this is deactivated.

can you provide an stats.txt example for testing?

**Comment by FabianSperrle** [comment]
Please check out the new version. It only features single language pages for now and worked well on the starterkit
