### ISSUE TITLE
Suggestion: add numbers to the percentages in widget

### ISSUE THREAD

**Issue by andi242** [FabianSperrle/kirby-stats#7]
...don't know why, but I am missing this somehow. :)

**Comment by FabianSperrle** [comment]
you mean the absolute numbers? As in 40 (12%)? Or rather 12% (40)?
Maybe this could be another option...

**Comment by andi242** [comment]
yes, absolute numbers.

I'd go for `40 (12%)`, but that's a personal preference :)
