### ISSUE TITLE
changed path to charts.js in latest commit

### ISSUE THREAD

**Issue by andi242** [FabianSperrle/kirby-stats#8]
please change `<?php echo js("assets/js/Chart.js"); ?>` in template.php or rename chart.js :)

(i have no idea how to do this with github on my own.)

**Comment by FabianSperrle** [comment]
You would have to fork the repository, make the changes and submit a pull request..

Anyway, it's done. Now am actually developing in this repo too and not just copying my changes in so stuff like that shouldn't happen anymore hopefully...

**Comment by andi242** [comment]
will actually try to "use" github the right way. thanks. ;)
